nelmio_cors:
    defaults:
        allow_origin: 
        - 'https://tienda-ropa-frontend.vercel.app'
        - 'http://localhost:5173'
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        expose_headers: []
        # Habilita Private Network Access para permitir preflight con ACA-Private-Network
        allow_private_network: true
    paths:
        '^/api/':
            allow_origin: 
                - 'https://tienda-ropa-frontend.vercel.app'
                - 'http://localhost:5173'
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600
            # Aquí también puedes reforzar si es necesario
            allow_private_network: true
